# Generated by Django 3.2.6 on 2021-11-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0002_auto_20211031_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('good_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trade.good')),
                ('degree', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            bases=('trade.good',),
        ),
    ]
