# Generated by Django 3.2.6 on 2021-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pochtron", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcohol",
            name="degree",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="alcohol",
            name="volume",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
