# Generated by Django 3.2.12 on 2022-08-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_auto_20220811_2021"),
        ("pochtron", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PochtronAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asign", models.BooleanField(default=False)),
                ("credit", models.BooleanField(default=False)),
                ("alcohol", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.student"
                    ),
                ),
            ],
        ),
    ]
