# Generated by Django 3.2.12 on 2022-08-12 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pochtron", "0002_pochtronadmin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pochtronadmin",
            old_name="asign",
            new_name="manage_admin",
        ),
    ]
