# Generated by Django 3.2.12 on 2022-08-12 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pochtron", "0003_rename_asign_pochtronadmin_manage_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pochtronadmin",
            old_name="manage_admin",
            new_name="manage_admins",
        ),
    ]
