# Generated by Django 3.2.12 on 2022-08-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_auto_20220811_2021"),
        ("pochtron", "0004_rename_manage_admin_pochtronadmin_manage_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pochtronadmin",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="social.student"
            ),
        ),
    ]
