# Generated by Django 3.2.12 on 2022-08-16 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pochtron", "0005_alter_pochtronadmin_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PochtronAdmin",
        ),
    ]
