# Generated by Django 3.2.12 on 2023-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pochtron", "0006_delete_pochtronadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
