version: "3.6"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./backups:/backups
  back:
    build:
      context: back
      dockerfile: Dockerfile
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
      - ./media:/media
      - bundles:/src/upont/static/react:rw
      - ./backups:/backups
    ports:
      - "$BACK_PORT:8000"
    depends_on:
      - db
      - webinstaller
    links:
      - db
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      ADMIN_EMAIL: $ADMIN_EMAIL
      DEFAULT_FROM_EMAIL: $DEFAULT_FROM_EMAIL
      SECRET_KEY: $SECRET_KEY
      DEBUG: $DEBUG
      DOMAIN_NAME: $DOMAIN_NAME
      REMOTE_STATIC_STORAGE: $REMOTE_STATIC_STORAGE
      FTP_STORAGE_LOCATION: $FTP_STORAGE_LOCATION
      REMOTE_STATIC_URL: $REMOTE_STATIC_URL
  webinstaller:
    build:
      context: ./
      dockerfile: ./webinstaller/Dockerfile
      target: development
    volumes:
      - ./react/:/app/:rw
      - bundles:/src/upont/static/react:rw
volumes:
  bundles:
    driver: local
