# Generated by Django 3.2.22 on 2023-11-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0012_student_is_moderator"),
        ("epicerie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("step", models.IntegerField(default=50)),
                ("max", models.IntegerField(default=5000)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Vrac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_date", models.DateTimeField()),
                ("close_date", models.DateTimeField()),
                ("pickup_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("ListProducts", models.ManyToManyField(to="epicerie.Product")),
            ],
        ),
        migrations.CreateModel(
            name="Vrac_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.JSONField(default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="social.student",
                    ),
                ),
                (
                    "vrac",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="epicerie.vrac",
                    ),
                ),
            ],
        ),
    ]
