# Generated by Django 3.2.22 on 2023-12-04 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epicerie", "0002_auto_20231130_1617"),
        ("epicerie", "0002_product_vrac_vrac_order"),
    ]

    operations = []
