# Generated by Django 3.2.22 on 2023-12-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epicerie", "0003_merge_20231204_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="vrac_order",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
