# Generated by Django 3.2.22 on 2023-12-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicerie', '0005_auto_20231220_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrac_order',
            name='order',
        ),
        migrations.AddField(
            model_name='prodcutorder',
            name='vracOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='epicerie.vrac_order'),
        ),
    ]
