# Generated by Django 3.2.22 on 2023-12-20 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epicerie", "0006_auto_20231220_1855"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProdcutOrder",
            new_name="ProductOrder",
        ),
    ]
