# Generated by Django 3.2.22 on 2023-12-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicerie', '0007_rename_prodcutorder_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='vracOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicerie.vrac_order'),
        ),
    ]
