# Generated by Django 3.2.22 on 2023-12-21 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0012_student_is_moderator"),
        ("epicerie", "0008_alter_productorder_vracorder"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Basket_Order",
            new_name="BasketOrder",
        ),
        migrations.RenameModel(
            old_name="Vrac_Order",
            new_name="VracOrder",
        ),
        migrations.AlterUniqueTogether(
            name="vracorder",
            unique_together={("vrac", "student")},
        ),
    ]
