# Generated by Django 3.2.22 on 2024-01-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epicerie", "0009_auto_20231221_1141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="composition",
        ),
        migrations.AddField(
            model_name="vegetable",
            name="basket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="epicerie.basket",
            ),
        ),
    ]
