# syntax=docker/dockerfile:1
FROM python:3.9.6-bullseye
ENV PYTHONUNBUFFERED=1
ENV VENV=/opt/venv
RUN python3 -m venv $VENV
ENV PATH="$VENV/bin:$PATH"

RUN apt update \
    && apt install -y apache2 apache2-dev

RUN echo \
"WSGIDaemonProcess upont python-path=/src python-home=/opt/venv/bin\n\
WSGIProcessGroup upont\n\
WSGIScriptAlias / /src/upont/wsgi.py\n\
<Directory /src/upont>\n\
<Files wsgi.py>\n\
Require all granted\n\
</Files>\n\
</Directory>\n\
<Directory /static>\n\
Require all granted\n\
</Directory>"\
>> /etc/apache2/apache2.conf

RUN apt install -y locales
RUN export LC_ALL="en_US.UTF-8" & export LC_CTYPE="en_US.UTF-8" & dpkg-reconfigure locales

WORKDIR /src
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD mod_wsgi-express start-server /src/upont/wsgi.py --user www-data --group www-data