# Generated by Django 3.2.6 on 2021-12-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_club_nickname"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="shotgun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.shotgun",
            ),
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shotgun_date", models.DateTimeField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shotgun",
            name="participations",
            field=models.ManyToManyField(
                blank=True, related_name="shotgun", to="news.Participation"
            ),
        ),
    ]
