# Generated by Django 3.2.12 on 2022-08-26 09:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
