# Generated by Django 3.2.6 on 2021-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_auto_20211206_1500"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shotgun",
            old_name="date",
            new_name="starting_date",
        ),
        migrations.AddField(
            model_name="shotgun",
            name="ending_date",
            field=models.DateTimeField(null=True),
        ),
    ]
