# Generated by Django 3.2.12 on 2022-08-27 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_event_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="duration",
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
