# Generated by Django 3.2.12 on 2023-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_merge_0004_auto_20220826_1123_0006_alter_role_name"),
        ("news", "0004_post_dislikes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="post_dislikes",
                to="social.Student",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, editable=False, related_name="posts", to="social.Student"
            ),
        ),
    ]
