# Generated by Django 3.2.6 on 2021-12-17 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_auto_20211210_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="shotgun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.shotgun",
            ),
        ),
    ]
