# Generated by Django 3.2.6 on 2021-12-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_event_shotgun"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="failed_motivation",
            field=models.BooleanField(default=False),
        ),
    ]
