# Generated by Django 3.2.12 on 2023-07-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_notificationtoken'),
        ('news', '0005_auto_20230117_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('visibility', models.CharField(choices=[('École', 'School'), ('Publique', 'Public'), ('Privée', 'Private')], default='Privée', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrateur', 'Admin'), ('Modérateur', 'Moderator'), ('Membre', 'Member'), ('Visiteur', 'Visitor')], default='Visiteur', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.page')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.student')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.page'),
        ),
    ]
