# Generated by Django 3.2.12 on 2023-11-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0015_alter_student_biography"),
        ("news", "0006_post_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="isPrice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="isShotgun",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="social.student",
                verbose_name="organizer",
            ),
        ),
        migrations.AddField(
            model_name="shotgun",
            name="failure_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shotgun",
            name="success_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
