# Generated by Django 3.2.6 on 2022-01-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_participation_failed_motivation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shotgun",
            name="participations",
        ),
        migrations.AddField(
            model_name="participation",
            name="shotgun",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.shotgun",
            ),
        ),
    ]
