# Generated by Django 3.2.6 on 2022-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_auto_20220103_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotgun",
            name="motivations_review_finished",
            field=models.BooleanField(default=False),
        ),
    ]
