# Generated by Django 3.2.12 on 2023-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20231124_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='isShotgun',
            field=models.BooleanField(default=False),
        ),
    ]
