# Generated by Django 3.2.22 on 2023-12-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0016_alter_club_nickname"),
        ("news", "0009_auto_20231124_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                ("id",
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name="ID",
                 ),
                 ),
                ("title",
                 models.CharField(
                     max_length=50)),
                ("image",
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to="ressources"),
                 ),
                ("video_url",
                 models.URLField(
                     blank=True,
                     null=True)),
                ("author",
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to="social.student",
                     verbose_name="author",
                 ),
                 ),
                ("post",
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name="ressources",
                     to="news.post",
                 ),
                 ),
            ],
        ),
    ]
