# Generated by Django 3.2.22 on 2024-08-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_ressource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressource",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/ressources"),
        ),
        migrations.AlterField(
            model_name="ressource",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="news.post",
            ),
        ),
    ]
