# Generated by Django 3.2.22 on 2025-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0019_alter_student_is_validated"),
        ("news", "0012_partnership"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("participant", "shotgun")},
        ),
    ]
