# Generated by Django 3.2.22 on 2025-05-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_alter_club_nickname"),
        ("news", "0013_auto_20250517_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="sondage",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="social.student",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="sondage",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
