# Generated by Django 3.2.22 on 2025-05-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_auto_20250517_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sondage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="sondage",
            name="club",
        ),
        migrations.RemoveField(
            model_name="votesondage",
            name="sondage",
        ),
        migrations.RemoveField(
            model_name="votesondage",
            name="vote",
        ),
        migrations.RemoveField(
            model_name="votesondage",
            name="voter",
        ),
        migrations.DeleteModel(
            name="OptionSondage",
        ),
        migrations.DeleteModel(
            name="Sondage",
        ),
        migrations.DeleteModel(
            name="VoteSondage",
        ),
    ]
