# Generated by Django 3.2.12 on 2023-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_auto_20221212_1511"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="courses.Teacher"
            ),
        ),
    ]
