# Generated by Django 3.2.12 on 2023-01-02 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_merge_0004_auto_20220826_1123_0006_alter_role_name"),
        ("news", "0003_auto_20220827_1112"),
        ("courses", "0003_resources"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resources",
            new_name="Resource",
        ),
    ]
