# Generated by Django 3.2.12 on 2023-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("place", models.CharField(blank=True, max_length=50)),
                (
                    "course_groups",
                    models.ManyToManyField(
                        blank=True, related_name="timeslot", to="courses.Group"
                    ),
                ),
            ],
        ),
    ]
