# Generated by Django 3.2.12 on 2023-01-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_rename_resources_resource"),
        ("courses", "0004_timeslot"),
    ]

    operations = []
