# Generated by Django 3.2.12 on 2023-01-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_merge_0004_rename_resources_resource_0004_timeslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
