# Generated by Django 3.2.12 on 2023-02-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_auto_20230117_2329"),
        ("courses", "0007_auto_20230117_2329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource",
                to="news.post",
                verbose_name="post",
            ),
        ),
    ]
