# Generated by Django 3.2.12 on 2023-02-15 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_auto_20230212_2026"),
        ("courses", "0007_auto_20230117_2329"),
    ]

    operations = []
