# Generated by Django 3.2.12 on 2023-02-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_resource_post"),
        ("courses", "0010_alter_course_teacher"),
    ]

    operations = []
