# Generated by Django 3.2.12 on 2023-09-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0007_merge_0004_auto_20220826_1123_0006_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_from_ponts', models.BooleanField()),
                ('rent_without_charges', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('description', models.TextField()),
                ('illustration', models.ImageField(upload_to='room_illustrations')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.student')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('illustration', models.ImageField(upload_to='apartment_illustrations')),
                ('localisation', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=200)),
                ('rooms', models.ManyToManyField(blank=True, to='colocaponts.Room')),
            ],
        ),
    ]
