# Generated by Django 3.2.22 on 2024-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="borrower",
            field=models.IntegerField(default=-1),
        ),
    ]
