# Generated by Django 3.2.22 on 2024-08-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_bike_borrower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bike",
            old_name="borrower",
            new_name="borrower_id",
        ),
    ]
