# Generated by Django 3.2.22 on 2025-02-27 12:28

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_rename_borrower_bike_borrower_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "products",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "prices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(
                                validators=[
                                    django.core.validators.MinValueValidator(0.0)
                                ]
                            ),
                            blank=True,
                            default=list,
                            size=None,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "quantity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.IntegerField(
                                validators=[django.core.validators.MinValueValidator(0)]
                            ),
                            blank=True,
                            default=list,
                            size=None,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vrac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("vrac", "Vrac"), ("unite", "Unité")], max_length=5
                    ),
                ),
                (
                    "price",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(
                            validators=[django.core.validators.MinValueValidator(0.0)]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "stock",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[django.core.validators.MinValueValidator(0)]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "stock_available",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[django.core.validators.MinValueValidator(0)]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
