# Generated by Django 3.2.22 on 2025-02-27 12:34

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_order_vrac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"))],
                    ),
                    blank=True,
                    default=list,
                    size=None,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="vrac",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(
                    decimal_places=2,
                    max_digits=10,
                    validators=[
                        django.core.validators.MinValueValidator(
                            Decimal("0.00"))],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
