# Generated by Django 3.2.22 on 2025-02-27 12:39

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_auto_20250227_1334"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="prices",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(
                            decimal_places=2,
                            max_digits=10,
                            validators=[
                                django.core.validators.MinValueValidator(
                                    Decimal("0.00")
                                )
                            ],
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "quantities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[django.core.validators.MinValueValidator(0)]
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.order"
                    ),
                ),
                (
                    "vrac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.vrac"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", through="services.OrderItem", to="services.Vrac"
            ),
        ),
    ]
