# Generated by Django 3.2.22 on 2025-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_auto_20250227_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="id_user",
            field=models.IntegerField(default=-1),
        ),
    ]
