# Generated by Django 3.2.6 on 2021-10-30 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Club', max_length=50)),
                ('nickname', models.CharField(default='Club', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('has_fee', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.category')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Française', max_length=30)),
                ('short_nationality', models.CharField(default='FR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(default='default', max_length=50)),
                ('nickname', models.CharField(default='000', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Membre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IMI', 'Ingénierie mathématique et informatique'), ('GCC', 'Génie civil et construction'), ('GMM', 'Génie mécanique et matériaux'), ('SEGF', 'Sciences économiques, gestion, finance'), ('VET', 'Ville, environnement, transport'), ('GI', 'Génie industriel'), ('1A', 'Première année')], default='1A', max_length=4)),
                ('gender', models.CharField(choices=[('Femme', 'F'), ('Homme', 'H'), ('Autre', 'A')], default='Autre', max_length=5)),
                ('origin', models.CharField(choices=[('Concours Commun', 'Cc')], default='Concours Commun', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro doit être entré au format: '+999999999'. Jusqu'à 16 chiffres sont autorisés.", regex='^\\+?\\d{9,16}$')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.nationality')),
                ('promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.promotion')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.club')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.role')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.student')),
            ],
        ),
    ]
