# Generated by Django 3.2.6 on 2021-10-29 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default='Française', max_length=30)),
                ('short_nationality', models.CharField(default='FR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(default='default', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Membre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Ingénierie mathématique et informatique', 'Imi'), ('Génie civil et construction', 'Gcc'), ('Génie mécanique et matériaux', 'Gmm'), ('Sciences économiques, gestion, finance', 'Segf'), ('Ville, environnement, transport', 'Vet'), ('Génie industriel', 'Gi'), ('Première année', 'A1')], default='Première année', max_length=50)),
                ('short_department', models.CharField(choices=[('IMI', 'Imi'), ('GCC', 'Gcc'), ('GMM', 'Gmm'), ('SEGF', 'Segf'), ('VET', 'Vet'), ('GI', 'Gi'), ('1A', 'A1')], default='Première année', max_length=4)),
                ('gender', models.CharField(choices=[('Femme', 'F'), ('Homme', 'H'), ('Autre', 'A')], default='Autre', max_length=5)),
                ('origin', models.CharField(choices=[('Concours Commun', 'Cc')], default='Concours Commun', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro doit être entré au format: '+999999999'. Jusqu'à 16 chiffres sont autorisés.", regex='^\\+?\\d{9,16}$')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('clubs', models.ManyToManyField(to='social.Membership')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.nationality')),
                ('promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.promotion')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.role'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Club', max_length=50)),
                ('nickname', models.CharField(default='Club', max_length=10)),
                ('logo', models.ImageField(upload_to='logos')),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('has_fee', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.category')),
                ('members', models.ManyToManyField(to='social.Membership')),
            ],
        ),
    ]
