# Generated by Django 3.2.6 on 2021-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IMI', 'Ingénierie mathématique et informatique'), ('GCC', 'Génie civil et construction'), ('GMM', 'Génie mécanique et matériaux'), ('SEGF', 'Sciences économiques, gestion, finance'), ('VET', 'Ville, environnement, transport')], max_length=4)),
            ],
        ),
    ]
