# Generated by Django 3.2.6 on 2021-10-28 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Femme', 'F'), ('Homme', 'H'), ('Autre', 'A')], default='Autre', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='origin',
            field=models.CharField(choices=[('Concours Commun', 'Cc')], default='Concours Commun', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro doit être entré au format: '+999999999'. Jusqu'à 16 chiffres sont autorisés.", regex='^\\+?\\d{9,16}$')]),
        ),
    ]
