# Generated by Django 3.2.6 on 2021-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211031_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='student',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(to='social.Membership'),
        ),
        migrations.AddField(
            model_name='student',
            name='clubs',
            field=models.ManyToManyField(to='social.Membership'),
        ),
    ]
