# Generated by Django 3.2.6 on 2021-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_auto_20211108_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="nickname",
            field=models.CharField(
                blank=True, default="Club", max_length=10, null=True
            ),
        ),
    ]
