# Generated by Django 3.2.12 on 2022-09-29 14:12

from typing import List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_auto_20220218_1519"),
        ("social", "0004_auto_20220811_2021"),
    ]

    operations: List[migrations.AlterField] = []
