# Generated by Django 3.2.12 on 2022-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_auto_20220811_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hasloggedin",
            field=models.BooleanField(default=False),
        ),
    ]
