# Generated by Django 3.2.10 on 2022-01-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_club_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='background_picture'),
        ),
    ]
