# Generated by Django 3.2.12 on 2022-11-16 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_auto_20220826_1123"),
        ("social", "0006_alter_role_name"),
    ]

    operations = []
