# Generated by Django 3.2.12 on 2023-09-09 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0008_notificationtoken"),
        ("social", "0009_add_birthdate_and_bio"),
    ]

    operations = []
