# Generated by Django 3.2.22 on 2023-10-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0011_alter_student_birthdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.club"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="subscriptions",
            field=models.ManyToManyField(
                through="social.Subscription", to="social.Club"
            ),
        ),
    ]
