# Generated by Django 3.2.22 on 2023-10-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0011_alter_student_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
