# Generated by Django 3.2.12 on 2023-10-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0012_student_is_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="label",
            field=models.CharField(
                choices=[
                    ("Association", "Asso"),
                    ("Club", "Club"),
                    ("Liste", "Liste"),
                    ("Inactif", "Inactif"),
                ],
                default="Club",
                max_length=20,
            ),
        ),
    ]
