# Generated by Django 3.2.12 on 2023-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0013_club_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="label",
            field=models.CharField(
                choices=[
                    ("Association", "Asso"),
                    ("Club", "Club"),
                    ("Liste", "Liste"),
                    ("Pôle", "Pole"),
                ],
                default="Club",
                max_length=20,
            ),
        ),
    ]
