# Generated by Django 3.2.22 on 2024-02-12 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_club_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être entré au format: '+999999999'. Jusqu'à 16 chiffres sont autorisés.", regex='^\\+?\\d{9,16}$')])),
                ('email', models.EmailField(max_length=254)),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.student')),
            ],
        ),
    ]
