# Generated by Django 3.2.22 on 2025-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_club_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='public_key',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_validated",
            field=models.BooleanField(default=True),
        ),
    ]
