# Generated by Django 3.2.22 on 2025-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_alter_club_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_validated",
            field=models.BooleanField(default=True),
        ),
    ]
