# Generated by Django 3.2.22 on 2025-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_student_is_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_connection",
            field=models.BooleanField(default=True),
        ),
    ]
