# Generated by Django 3.2.22 on 2024-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='student',
        ),
    ]
