# Generated by Django 3.2.22 on 2024-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20240212_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='contact_photo/'),
        ),
    ]
