# Generated by Django 3.2.22 on 2025-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0021_auto_20250530_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_connection",
            field=models.BooleanField(default=True),
        ),
    ]
