# Generated by Django 3.2.22 on 2026-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_student_first_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IMI', 'Ingénierie mathématique et informatique'), ('GCC', 'Génie civil et construction'), ('GMM', 'Génie mécanique et matériaux'), ('SEGF', 'Sciences économiques, gestion, finance'), ('VET', 'Ville, environnement, transport'), ('GI', 'Génie industriel'), ('1A', 'Première année'), ('Doct', 'Doctorant'), ('Mast', 'Master')], default='1A', max_length=4),
        ),
    ]
