# Generated by Django 3.2.22 on 2026-02-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelencryptedkey',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
