# Generated by Django 3.2.22 on 2026-02-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20260228_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Refusee')], default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='social.channel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_join_requests', to='social.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channeljoinrequest',
            constraint=models.UniqueConstraint(fields=('channel', 'student'), name='unique_channel_join_request'),
        ),
    ]
