# Generated by Django 3.2.6 on 2021-10-31 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20211031_2321'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='club',
        ),
        migrations.AddField(
            model_name='good',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.club'),
        ),
    ]
