# Generated by Django 3.2.12 on 2022-08-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_auto_20220811_2021"),
        ("trade", "0002_auto_20220225_0844"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manage_admins", models.BooleanField(default=False)),
                ("manage_goods", models.BooleanField(default=False)),
                ("manage_transactions", models.BooleanField(default=False)),
                ("manage_credits", models.BooleanField(default=False)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.club"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="social.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "club")},
            },
        ),
    ]
